---
controller_templates:
    - name: "CaC | AAP Configify"
      description: Test
      playbook: aap_configify.yml
      execution_environment: Default execution environment
      project: ansible-cac
      inventory: Demo Inventory
      job_slice_count: 1
      job_type: run